# 服务端口号
server:
  port: 8899

# log日志
logging:
#  日志路径
  path: logs
#  文件名
  file: myLogs.log

# spring配置
spring:
  application:
#    程序名字
    name: userManager
#    数据库配置
  datasource:
#    数据库驱动
    driver-class-name: com.mysql.cj.jdbc.Driver
#    数据库地址
    url: jdbc:mysql://localhost:3306/course?userUnicode=ture&characterEncoding=utf-8&useSSL=true
#    数据库用户名
    username: root
#    数据库密码
    password: 123456

# 配置MyBatis
mybatis:
#  包路径
  type-aliases-package: com.course.model
#  mapper文件路径
  mapper-locations:
    - mapper/*
